# This is a basic workflow to help you get started with Actions

name: Spring Boot CI/CD Github Actions

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git 
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3.2.0
        with:
         distribution: 'adopt'
         java-version: '11'
         server-id: docker.io
         server-username: venkat7010
         server-password: Dockerhub@529
      
      - name: Build and Push department-service
        run: mvn package dockerfile:push --file department-service/pom.xml
        env:
          MAVEN_USERNAME: venkat7010
          MAVEN_PASSWORD: Dockerhub@529
