# This is a basic workflow to help you get started with Actions

name: Spring Boot CI/CD Github Actions

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git 
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '11' 
      
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: venkat7010
          password: Dockerhub@529
      
      - name: Building Maven Eureka Server Package
        run: mvn -B package --file eureka-server/pom.xml
      - name: Build and push Eureka Service to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./eureka-server
          tags: venkat7010/eureka-server:0.0.1
      
      - name: Building Maven Cloud Config Server Package
        run: mvn -B package --file cloud-config-server/pom.xml
      - name: Build and push Cloud Config Server to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./cloud-config-server
          tags: venkat7010/cloud-config-server:0.0.1
        
  
      - name: Building Maven Department Service Package
        run: mvn -B package --file department-service/pom.xml
      - name: Build and push Department Service to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./department-service
          tags: venkat7010/department-service:0.0.1  
          
      - name: Building Maven Employee Service Package
        run: mvn -B package --file employee-service/pom.xml
      - name: Build and push Employee Service to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./employee-service
          tags: venkat7010/employee-service:0.0.1
      
        
      - name: Building Maven Cloud Gateway Package
        run: mvn -B package --file employee-service/pom.xml
      - name: Build and push Cloud Gateway to DockerHub
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./cloud-gateway
          tags: venkat7010/cloud-gateway:0.0.1
      
     
      
