# This is a basic workflow to help you get started with Actions

name: Spring Boot CI/CD Github Actions

on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:

  build:
 
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Git 
        uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
         distribution: 'adopt'
         java-version: '11' 
      - name: Building and Pushing Employee Service
        run: mvn -B package --file employee-service/pom.xml
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: venkat7010
          password: Dockerhub@529
      - name: Build and push 
        uses: docker/build-push-action@v2
        with:
          push: true
          context: ./employee-service
          tags: venkat7010/employee-service:latest
